syntax = "proto3";

package master;

option go_package = "github.com/mapreduce_impl/rpc";

service MasterService {
  rpc WorkerRegister(WorkerRegisterRequest) returns (WorkerRegisterReply);
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatReply);
  rpc TaskApply(TaskApplyRequest) returns (TaskApplyReply);
  rpc TaskCompletion(TaskCompletionRequest) returns (TaskCompletionReply);
}

// worker 向 master 发送自己的标识信息和地址
message WorkerRegisterRequest {
  string worker_id = 1;
  string address = 2;
  int32 generation = 3;   // 可选，空值为 0
}

// Map 阶段需要 NReduce 计算分区：partition = hash(key) % nReduce。相同的 key 进入相同的 分区
message WorkerRegisterReply {
  Signal signal = 1;
  string master_id = 2;
  int32 generation = 3;
}


enum Signal {
  OK = 0;
  REGISTER = 1;
  SHUTDOWN = 2;
  WAIT = 3;
}

// Heartbeat
message HeartbeatRequest {
  string worker_id = 1;
  int32 generation = 2;
}

message HeartbeatReply {
  Signal signal = 1;
}

// TaskApply
message TaskApplyRequest {
  string worker_id = 1;
  int32 generation = 2;
}

message TaskApplyReply {
  Signal signal = 1;
  int32 task_id = 2;
  TaskType task_type = 3;
  oneof task_info {
    MapTaskInfo map_task_info = 4;
    ReduceTaskInfo reduce_task_info = 5;
  }
}


enum TaskType {
  MAP = 0;
  REDUCE = 1;
}


// 
message MapTaskInfo {
  InputFormatter input_formatter = 1;
  int32 partition_count = 2;
  string intermediate_dir = 3;
}



message ReduceTaskInfo {
  int32 partition_index = 1;
  repeated string partition_paths = 2;
  string output_dir = 3;
}



message InputFormatter {
  string input_path = 1;
  int32 from = 2;
  int32 to = 3;
}

// TaskCompletion
message TaskCompletionRequest {
  string worker_id = 1;
  int32 generation = 2;
  int32 task_id = 3;
  TaskType task_type = 4;
  oneof attach {
    CompletionMapAttach map_attach = 5;
    CompletionReduceAttach reduce_attach = 6;
  }
}

message TaskCompletionReply {
  Signal signal = 1;
}
message CompletionMapAttach {
  repeated string intermediate_paths = 1;  // 文件路径由： ip:port/path/file_name
}

message CompletionReduceAttach {
  string output_path = 1;
}
