// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rpc/master.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signal int32

const (
	Signal_OK       Signal = 0
	Signal_REGISTER Signal = 1
	Signal_SHUTDOWN Signal = 2
	Signal_WAIT     Signal = 3
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0: "OK",
		1: "REGISTER",
		2: "SHUTDOWN",
		3: "WAIT",
	}
	Signal_value = map[string]int32{
		"OK":       0,
		"REGISTER": 1,
		"SHUTDOWN": 2,
		"WAIT":     3,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_master_proto_enumTypes[0].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_rpc_master_proto_enumTypes[0]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_MAP    TaskType = 0
	TaskType_REDUCE TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "MAP",
		1: "REDUCE",
	}
	TaskType_value = map[string]int32{
		"MAP":    0,
		"REDUCE": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_master_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_rpc_master_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{1}
}

// worker 向 master 发送自己的标识信息和地址
type WorkerRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Generation    int32                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"` // 可选，空值为 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegisterRequest) Reset() {
	*x = WorkerRegisterRequest{}
	mi := &file_rpc_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegisterRequest) ProtoMessage() {}

func (x *WorkerRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegisterRequest.ProtoReflect.Descriptor instead.
func (*WorkerRegisterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkerRegisterRequest) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// Map 阶段需要 NReduce 计算分区：partition = hash(key) % nReduce。相同的 key 进入相同的 分区
type WorkerRegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        Signal                 `protobuf:"varint,1,opt,name=signal,proto3,enum=master.Signal" json:"signal,omitempty"`
	MasterId      string                 `protobuf:"bytes,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Generation    int32                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegisterReply) Reset() {
	*x = WorkerRegisterReply{}
	mi := &file_rpc_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegisterReply) ProtoMessage() {}

func (x *WorkerRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegisterReply.ProtoReflect.Descriptor instead.
func (*WorkerRegisterReply) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerRegisterReply) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_OK
}

func (x *WorkerRegisterReply) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *WorkerRegisterReply) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    int32                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_rpc_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        Signal                 `protobuf:"varint,1,opt,name=signal,proto3,enum=master.Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_rpc_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatReply) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_OK
}

// TaskApply
type TaskApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    int32                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskApplyRequest) Reset() {
	*x = TaskApplyRequest{}
	mi := &file_rpc_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskApplyRequest) ProtoMessage() {}

func (x *TaskApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskApplyRequest.ProtoReflect.Descriptor instead.
func (*TaskApplyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{4}
}

func (x *TaskApplyRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskApplyRequest) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type TaskApplyReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Signal   Signal                 `protobuf:"varint,1,opt,name=signal,proto3,enum=master.Signal" json:"signal,omitempty"`
	TaskId   int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=master.TaskType" json:"task_type,omitempty"`
	// Types that are valid to be assigned to TaskInfo:
	//
	//	*TaskApplyReply_MapTaskInfo
	//	*TaskApplyReply_ReduceTaskInfo
	TaskInfo      isTaskApplyReply_TaskInfo `protobuf_oneof:"task_info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskApplyReply) Reset() {
	*x = TaskApplyReply{}
	mi := &file_rpc_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskApplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskApplyReply) ProtoMessage() {}

func (x *TaskApplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskApplyReply.ProtoReflect.Descriptor instead.
func (*TaskApplyReply) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{5}
}

func (x *TaskApplyReply) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_OK
}

func (x *TaskApplyReply) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskApplyReply) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_MAP
}

func (x *TaskApplyReply) GetTaskInfo() isTaskApplyReply_TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *TaskApplyReply) GetMapTaskInfo() *MapTaskInfo {
	if x != nil {
		if x, ok := x.TaskInfo.(*TaskApplyReply_MapTaskInfo); ok {
			return x.MapTaskInfo
		}
	}
	return nil
}

func (x *TaskApplyReply) GetReduceTaskInfo() *ReduceTaskInfo {
	if x != nil {
		if x, ok := x.TaskInfo.(*TaskApplyReply_ReduceTaskInfo); ok {
			return x.ReduceTaskInfo
		}
	}
	return nil
}

type isTaskApplyReply_TaskInfo interface {
	isTaskApplyReply_TaskInfo()
}

type TaskApplyReply_MapTaskInfo struct {
	MapTaskInfo *MapTaskInfo `protobuf:"bytes,4,opt,name=map_task_info,json=mapTaskInfo,proto3,oneof"`
}

type TaskApplyReply_ReduceTaskInfo struct {
	ReduceTaskInfo *ReduceTaskInfo `protobuf:"bytes,5,opt,name=reduce_task_info,json=reduceTaskInfo,proto3,oneof"`
}

func (*TaskApplyReply_MapTaskInfo) isTaskApplyReply_TaskInfo() {}

func (*TaskApplyReply_ReduceTaskInfo) isTaskApplyReply_TaskInfo() {}

type MapTaskInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputFormatter  *InputFormatter        `protobuf:"bytes,1,opt,name=input_formatter,json=inputFormatter,proto3" json:"input_formatter,omitempty"`
	PartitionCount  int32                  `protobuf:"varint,2,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	IntermediateDir string                 `protobuf:"bytes,3,opt,name=intermediate_dir,json=intermediateDir,proto3" json:"intermediate_dir,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapTaskInfo) Reset() {
	*x = MapTaskInfo{}
	mi := &file_rpc_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTaskInfo) ProtoMessage() {}

func (x *MapTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTaskInfo.ProtoReflect.Descriptor instead.
func (*MapTaskInfo) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{6}
}

func (x *MapTaskInfo) GetInputFormatter() *InputFormatter {
	if x != nil {
		return x.InputFormatter
	}
	return nil
}

func (x *MapTaskInfo) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *MapTaskInfo) GetIntermediateDir() string {
	if x != nil {
		return x.IntermediateDir
	}
	return ""
}

type ReduceTaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionIndex int32                  `protobuf:"varint,1,opt,name=partition_index,json=partitionIndex,proto3" json:"partition_index,omitempty"`
	PartitionPaths []string               `protobuf:"bytes,2,rep,name=partition_paths,json=partitionPaths,proto3" json:"partition_paths,omitempty"`
	OutputDir      string                 `protobuf:"bytes,3,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReduceTaskInfo) Reset() {
	*x = ReduceTaskInfo{}
	mi := &file_rpc_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceTaskInfo) ProtoMessage() {}

func (x *ReduceTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceTaskInfo.ProtoReflect.Descriptor instead.
func (*ReduceTaskInfo) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{7}
}

func (x *ReduceTaskInfo) GetPartitionIndex() int32 {
	if x != nil {
		return x.PartitionIndex
	}
	return 0
}

func (x *ReduceTaskInfo) GetPartitionPaths() []string {
	if x != nil {
		return x.PartitionPaths
	}
	return nil
}

func (x *ReduceTaskInfo) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

type InputFormatter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputPath     string                 `protobuf:"bytes,1,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFormatter) Reset() {
	*x = InputFormatter{}
	mi := &file_rpc_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFormatter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFormatter) ProtoMessage() {}

func (x *InputFormatter) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFormatter.ProtoReflect.Descriptor instead.
func (*InputFormatter) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{8}
}

func (x *InputFormatter) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *InputFormatter) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *InputFormatter) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

// TaskCompletion
type TaskCompletionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkerId   string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation int32                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	TaskId     int32                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType   TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=master.TaskType" json:"task_type,omitempty"`
	// Types that are valid to be assigned to Attach:
	//
	//	*TaskCompletionRequest_MapAttach
	//	*TaskCompletionRequest_ReduceAttach
	Attach        isTaskCompletionRequest_Attach `protobuf_oneof:"attach"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionRequest) Reset() {
	*x = TaskCompletionRequest{}
	mi := &file_rpc_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionRequest) ProtoMessage() {}

func (x *TaskCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionRequest.ProtoReflect.Descriptor instead.
func (*TaskCompletionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{9}
}

func (x *TaskCompletionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskCompletionRequest) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TaskCompletionRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskCompletionRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_MAP
}

func (x *TaskCompletionRequest) GetAttach() isTaskCompletionRequest_Attach {
	if x != nil {
		return x.Attach
	}
	return nil
}

func (x *TaskCompletionRequest) GetMapAttach() *CompletionMapAttach {
	if x != nil {
		if x, ok := x.Attach.(*TaskCompletionRequest_MapAttach); ok {
			return x.MapAttach
		}
	}
	return nil
}

func (x *TaskCompletionRequest) GetReduceAttach() *CompletionReduceAttach {
	if x != nil {
		if x, ok := x.Attach.(*TaskCompletionRequest_ReduceAttach); ok {
			return x.ReduceAttach
		}
	}
	return nil
}

type isTaskCompletionRequest_Attach interface {
	isTaskCompletionRequest_Attach()
}

type TaskCompletionRequest_MapAttach struct {
	MapAttach *CompletionMapAttach `protobuf:"bytes,5,opt,name=map_attach,json=mapAttach,proto3,oneof"`
}

type TaskCompletionRequest_ReduceAttach struct {
	ReduceAttach *CompletionReduceAttach `protobuf:"bytes,6,opt,name=reduce_attach,json=reduceAttach,proto3,oneof"`
}

func (*TaskCompletionRequest_MapAttach) isTaskCompletionRequest_Attach() {}

func (*TaskCompletionRequest_ReduceAttach) isTaskCompletionRequest_Attach() {}

type TaskCompletionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        Signal                 `protobuf:"varint,1,opt,name=signal,proto3,enum=master.Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionReply) Reset() {
	*x = TaskCompletionReply{}
	mi := &file_rpc_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionReply) ProtoMessage() {}

func (x *TaskCompletionReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionReply.ProtoReflect.Descriptor instead.
func (*TaskCompletionReply) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{10}
}

func (x *TaskCompletionReply) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_OK
}

type CompletionMapAttach struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IntermediatePaths []string               `protobuf:"bytes,1,rep,name=intermediate_paths,json=intermediatePaths,proto3" json:"intermediate_paths,omitempty"` // 文件路径由： ip:port/path/file_name
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompletionMapAttach) Reset() {
	*x = CompletionMapAttach{}
	mi := &file_rpc_master_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionMapAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionMapAttach) ProtoMessage() {}

func (x *CompletionMapAttach) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionMapAttach.ProtoReflect.Descriptor instead.
func (*CompletionMapAttach) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{11}
}

func (x *CompletionMapAttach) GetIntermediatePaths() []string {
	if x != nil {
		return x.IntermediatePaths
	}
	return nil
}

type CompletionReduceAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputPath    string                 `protobuf:"bytes,1,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionReduceAttach) Reset() {
	*x = CompletionReduceAttach{}
	mi := &file_rpc_master_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionReduceAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionReduceAttach) ProtoMessage() {}

func (x *CompletionReduceAttach) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_master_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionReduceAttach.ProtoReflect.Descriptor instead.
func (*CompletionReduceAttach) Descriptor() ([]byte, []int) {
	return file_rpc_master_proto_rawDescGZIP(), []int{12}
}

func (x *CompletionReduceAttach) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

var File_rpc_master_proto protoreflect.FileDescriptor

const file_rpc_master_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/master.proto\x12\x06master\"n\n" +
	"\x15WorkerRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\"z\n" +
	"\x13WorkerRegisterReply\x12&\n" +
	"\x06signal\x18\x01 \x01(\x0e2\x0e.master.SignalR\x06signal\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\tR\bmasterId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\"O\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x05R\n" +
	"generation\"8\n" +
	"\x0eHeartbeatReply\x12&\n" +
	"\x06signal\x18\x01 \x01(\x0e2\x0e.master.SignalR\x06signal\"O\n" +
	"\x10TaskApplyRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x05R\n" +
	"generation\"\x8c\x02\n" +
	"\x0eTaskApplyReply\x12&\n" +
	"\x06signal\x18\x01 \x01(\x0e2\x0e.master.SignalR\x06signal\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x12-\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\x10.master.TaskTypeR\btaskType\x129\n" +
	"\rmap_task_info\x18\x04 \x01(\v2\x13.master.MapTaskInfoH\x00R\vmapTaskInfo\x12B\n" +
	"\x10reduce_task_info\x18\x05 \x01(\v2\x16.master.ReduceTaskInfoH\x00R\x0ereduceTaskInfoB\v\n" +
	"\ttask_info\"\xa2\x01\n" +
	"\vMapTaskInfo\x12?\n" +
	"\x0finput_formatter\x18\x01 \x01(\v2\x16.master.InputFormatterR\x0einputFormatter\x12'\n" +
	"\x0fpartition_count\x18\x02 \x01(\x05R\x0epartitionCount\x12)\n" +
	"\x10intermediate_dir\x18\x03 \x01(\tR\x0fintermediateDir\"\x81\x01\n" +
	"\x0eReduceTaskInfo\x12'\n" +
	"\x0fpartition_index\x18\x01 \x01(\x05R\x0epartitionIndex\x12'\n" +
	"\x0fpartition_paths\x18\x02 \x03(\tR\x0epartitionPaths\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x03 \x01(\tR\toutputDir\"S\n" +
	"\x0eInputFormatter\x12\x1d\n" +
	"\n" +
	"input_path\x18\x01 \x01(\tR\tinputPath\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x05R\x02to\"\xab\x02\n" +
	"\x15TaskCompletionRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x05R\n" +
	"generation\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x05R\x06taskId\x12-\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\x10.master.TaskTypeR\btaskType\x12<\n" +
	"\n" +
	"map_attach\x18\x05 \x01(\v2\x1b.master.CompletionMapAttachH\x00R\tmapAttach\x12E\n" +
	"\rreduce_attach\x18\x06 \x01(\v2\x1e.master.CompletionReduceAttachH\x00R\freduceAttachB\b\n" +
	"\x06attach\"=\n" +
	"\x13TaskCompletionReply\x12&\n" +
	"\x06signal\x18\x01 \x01(\x0e2\x0e.master.SignalR\x06signal\"D\n" +
	"\x13CompletionMapAttach\x12-\n" +
	"\x12intermediate_paths\x18\x01 \x03(\tR\x11intermediatePaths\"9\n" +
	"\x16CompletionReduceAttach\x12\x1f\n" +
	"\voutput_path\x18\x01 \x01(\tR\n" +
	"outputPath*6\n" +
	"\x06Signal\x12\x06\n" +
	"\x02OK\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\f\n" +
	"\bSHUTDOWN\x10\x02\x12\b\n" +
	"\x04WAIT\x10\x03*\x1f\n" +
	"\bTaskType\x12\a\n" +
	"\x03MAP\x10\x00\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x012\xa9\x02\n" +
	"\rMasterService\x12L\n" +
	"\x0eWorkerRegister\x12\x1d.master.WorkerRegisterRequest\x1a\x1b.master.WorkerRegisterReply\x12=\n" +
	"\tHeartbeat\x12\x18.master.HeartbeatRequest\x1a\x16.master.HeartbeatReply\x12=\n" +
	"\tTaskApply\x12\x18.master.TaskApplyRequest\x1a\x16.master.TaskApplyReply\x12L\n" +
	"\x0eTaskCompletion\x12\x1d.master.TaskCompletionRequest\x1a\x1b.master.TaskCompletionReplyB\x1fZ\x1dgithub.com/mapreduce_impl/rpcb\x06proto3"

var (
	file_rpc_master_proto_rawDescOnce sync.Once
	file_rpc_master_proto_rawDescData []byte
)

func file_rpc_master_proto_rawDescGZIP() []byte {
	file_rpc_master_proto_rawDescOnce.Do(func() {
		file_rpc_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_master_proto_rawDesc), len(file_rpc_master_proto_rawDesc)))
	})
	return file_rpc_master_proto_rawDescData
}

var file_rpc_master_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_master_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rpc_master_proto_goTypes = []any{
	(Signal)(0),                    // 0: master.Signal
	(TaskType)(0),                  // 1: master.TaskType
	(*WorkerRegisterRequest)(nil),  // 2: master.WorkerRegisterRequest
	(*WorkerRegisterReply)(nil),    // 3: master.WorkerRegisterReply
	(*HeartbeatRequest)(nil),       // 4: master.HeartbeatRequest
	(*HeartbeatReply)(nil),         // 5: master.HeartbeatReply
	(*TaskApplyRequest)(nil),       // 6: master.TaskApplyRequest
	(*TaskApplyReply)(nil),         // 7: master.TaskApplyReply
	(*MapTaskInfo)(nil),            // 8: master.MapTaskInfo
	(*ReduceTaskInfo)(nil),         // 9: master.ReduceTaskInfo
	(*InputFormatter)(nil),         // 10: master.InputFormatter
	(*TaskCompletionRequest)(nil),  // 11: master.TaskCompletionRequest
	(*TaskCompletionReply)(nil),    // 12: master.TaskCompletionReply
	(*CompletionMapAttach)(nil),    // 13: master.CompletionMapAttach
	(*CompletionReduceAttach)(nil), // 14: master.CompletionReduceAttach
}
var file_rpc_master_proto_depIdxs = []int32{
	0,  // 0: master.WorkerRegisterReply.signal:type_name -> master.Signal
	0,  // 1: master.HeartbeatReply.signal:type_name -> master.Signal
	0,  // 2: master.TaskApplyReply.signal:type_name -> master.Signal
	1,  // 3: master.TaskApplyReply.task_type:type_name -> master.TaskType
	8,  // 4: master.TaskApplyReply.map_task_info:type_name -> master.MapTaskInfo
	9,  // 5: master.TaskApplyReply.reduce_task_info:type_name -> master.ReduceTaskInfo
	10, // 6: master.MapTaskInfo.input_formatter:type_name -> master.InputFormatter
	1,  // 7: master.TaskCompletionRequest.task_type:type_name -> master.TaskType
	13, // 8: master.TaskCompletionRequest.map_attach:type_name -> master.CompletionMapAttach
	14, // 9: master.TaskCompletionRequest.reduce_attach:type_name -> master.CompletionReduceAttach
	0,  // 10: master.TaskCompletionReply.signal:type_name -> master.Signal
	2,  // 11: master.MasterService.WorkerRegister:input_type -> master.WorkerRegisterRequest
	4,  // 12: master.MasterService.Heartbeat:input_type -> master.HeartbeatRequest
	6,  // 13: master.MasterService.TaskApply:input_type -> master.TaskApplyRequest
	11, // 14: master.MasterService.TaskCompletion:input_type -> master.TaskCompletionRequest
	3,  // 15: master.MasterService.WorkerRegister:output_type -> master.WorkerRegisterReply
	5,  // 16: master.MasterService.Heartbeat:output_type -> master.HeartbeatReply
	7,  // 17: master.MasterService.TaskApply:output_type -> master.TaskApplyReply
	12, // 18: master.MasterService.TaskCompletion:output_type -> master.TaskCompletionReply
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rpc_master_proto_init() }
func file_rpc_master_proto_init() {
	if File_rpc_master_proto != nil {
		return
	}
	file_rpc_master_proto_msgTypes[5].OneofWrappers = []any{
		(*TaskApplyReply_MapTaskInfo)(nil),
		(*TaskApplyReply_ReduceTaskInfo)(nil),
	}
	file_rpc_master_proto_msgTypes[9].OneofWrappers = []any{
		(*TaskCompletionRequest_MapAttach)(nil),
		(*TaskCompletionRequest_ReduceAttach)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_master_proto_rawDesc), len(file_rpc_master_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_master_proto_goTypes,
		DependencyIndexes: file_rpc_master_proto_depIdxs,
		EnumInfos:         file_rpc_master_proto_enumTypes,
		MessageInfos:      file_rpc_master_proto_msgTypes,
	}.Build()
	File_rpc_master_proto = out.File
	file_rpc_master_proto_goTypes = nil
	file_rpc_master_proto_depIdxs = nil
}
